### ISSUE TITLE
Preliminary release checklist

### ISSUE THREAD

**Issue by corranwebster** [unital/tempe#28]
Should aim to do the following:

- [x] fill out the sections on scatter and polar plots
- [x] sort out fonts
- [x] add .pyi file for font.py
- [ ] ~document lines.py (and add thick line options to high-level API)~
- [x] add .pyi file for lines.py
- [ ] ~update more complex examples to use high-level API~
- [ ] ~add examples to the documentation~
- [x] what to do about components? (maybe move to examples for now?)
- [ ] ~clean up original example~
